# These are supported funding model platforms

github: [NikaShamiladze]
patreon: vue css
open_collective: veucss
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/veucss
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
